runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_g9kgx0z1:c8uc9nc6v8cqmqtv5hscvhved@ds027761.mlab.com:27761/heroku_g9kgx0z1
  APP_ID: myAppId
  MASTER_KEY: myMasterKey
  SERVER_URL: https://replyserver.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
